name: "Build Game"

on:
  workflow_call:
    inputs:
      game_name:
        required: true
        type: string
  workflow_dispatch:

env:
  GODOT_VERSION: "4.6"
  GODOT_EXPORT_VERSION: "4.6-stable"
  GAME_NAME: ${{ inputs.game_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: "üèóÔ∏è Build ${{ matrix.platform }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Web
            preset: Web
            needs_wine: false
          - platform: Windows
            preset: Windows Desktop
            needs_wine: true
          - platform: Linux
            preset: Linux
            needs_wine: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Wine
        if: matrix.needs_wine
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends wine64

      - name: Export Game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_EXPORT_VERSION }}/Godot_v${{ env.GODOT_EXPORT_VERSION }}_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_EXPORT_VERSION }}/Godot_v${{ env.GODOT_EXPORT_VERSION }}_export_templates.tpz
          relative_project_path: ./
          cache: true
          export_debug: false
          archive_output: true
          export_preset: ${{ matrix.preset }}
          wine_path: ${{ matrix.needs_wine && '/usr/bin/wine64' || '' }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.game_name }}-${{ matrix.platform }}
          path: ${{ steps.export.outputs.archive_directory }}/*
          retention-days: 30
